baseURL: "https://auravan.top/"
enableEmoji: true
hasCJKLanguage: true
ignoreFiles:
  - \.Rmarkdown$
  - \.Rmd$"
  - \.knit\.md$
  - \.utf8\.md$
  - _files$
  - _cache$
  - \.txt$
  - \.csv$
  - \.tsv$
  - \.tgz$
  - \.tar$
  - \.gz$
  - \.zip$
  - \.npz$
languageCode: "zh-cn"
title: "李崎滨 | Arua Van"
rssLimit: 100

# services:
#   googleAnalytics:
#     ID: "G-RJC7CCKE67"

permalinks:
  cn_aura: "/cn_aura/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"
  tech101: "/tech101/:year/:month/:slug/"
  rss: "/cn_aura/index.xml"

# taxonomies:
#   category: categories

menu:
  home:
    - name: "博客"
      url: "/cn_aura/"
      weight: 1
    # - identifier: "cn-menu-separator-1"
    #   url: "#menu-separator"
    #   weight: 2
    - name: "关于"
      url: "/cn/about/"
      weight: 3
    # - name: "研究"
      # url: "/research"
      # weight: 4
    # - name: "About"
    #   url: "/en1/about/"
    #   weight: 5
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "博客"
      url: "/cn_aura/"
      weight: 2
    - name: "分类"
      url: "/categories/"
      weight: 3
    - identifier: "cn-menu-separator-1"
      url: "#menu-separator"
      weight: 4
    - name: "绘画"
      url: "/painting/"
      weight: 5
    # - name: "烹饪"
    #   url: "/1cooking/"
    #   weight: 6
    # - name: "摩托"
    #   url: "/1motorcycle1/"
    #   weight: 7
    - name: "关于"
      url: "/cn/about/"
      weight: 8
    - name: "简历"
      url: "/cn/resume/"
      weight: 9
  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Blog"
      url: "/1en/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - identifier: "en-menu-separator-1"
      url: "#menu-separator"
      weight: 4
    - name: "About"
      url: "/en/about/"
      weight: 5
    - name: "Resume"
      url: "/en/resume/"
      weight: 6

params:
  description: "李崎滨的个人网站 | Build with blogdown"
  footer: "Copyright &copy; 2024-{Year} [李崎滨 | Aura Van]"
  # licenseURL: "https://github.com/leovan/leovan.me/blob/main/LICENSE"
  googleAdsense: "ca-pub-1217183586241699"
  categories: "分类 | Categories"

  aplayerVersion: "1.10.1"
  clipboardjsVersion: "2.0.11"
  imageCompareViewerVersion: "latest"
  jQueryVersion: "3.7.1"
  jsCookieVersion: "3.0.5"
  justifiedgalleryVersion: "3.8.1"
  lazysizesVersion: "5.3.2"
  lightgalleryVersion: "2.7.2"
  mathjaxVersion: "3.2"
  meetingjsVersion: "latest"
  pseudocodeVersion: "latest"
  prismjsVersion: "1.29.0"
  vanillaBackToTopVersion: "latest"
  videojsVersion: "8.13.0"

  lang:
    logo:
      en: "/images/web/icon-512x512.png"
      cn: "/images/web/icon-512x512.png"
    slogan:
      en: "more is different"
      cn: "己所不欲，勿施于人"
    author:
      en: "Aura Van"
      cn: "李崎滨"
    license:
      cn: "版权"
      en: "License"
    subscribe:
      cn: "订阅"
      en: "Subscribe"
    categories:
      cn: "分类"
      en: "Categories"
    tags:
      cn: "标签"
      en: "Tags"
    wordcount:
      cn: "字数"
      en: "Word Count"
    admonition:
      note:
        cn: "注意"
        en: "Note"
      abstract:
        cn: "摘要"
        en: "Abstract"
      info:
        cn: "信息"
        en: "Info"
      tip:
        cn: "提示"
        en: "Tip"
      success:
        cn: "成功"
        en: "Success"
      question:
        cn: "问题"
        en: "Question"
      warning:
        cn: "警告"
        en: "Warning"
      failure:
        cn: "失败"
        en: "Failure"
      danger:
        cn: "危险"
        en: "Danger"
      bug:
        cn: "错误"
        en: "Bug"
      example:
        cn: "示例"
        en: "Example"
      quote:
        cn: "引用"
        en: "Quote"
    donate:
      cn: "赞 赏"
      en: "DONATE"
    donate_slogan:
      cn: "「往来无百丁，请君备注留姓名（wx)」"
      en: "「Donation Given, Fragrance in Hand」"
    donate_2_cny:
      cn: "2 元"
      en: "2 CNY"
    donate_5_cny:
      cn: "5 元"
      en: "5 CNY"
    donate_10_cny:
      cn: "10 元"
      en: "10 CNY"
    donate_50_cny:
      cn: "50 元"
      en: "50 CNY"
    donate_100_cny:
      cn: "100 元"
      en: "100 CNY"
    donate_custom_cny:
      cn: "任意金额"
      en: "CUSTOM"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
    endLevel: 4 
